### ISSUE TITLE
Increase automated test coverage

### ISSUE THREAD

**Issue by aimeevitacbsi** [cbsinteractive/hawkeye#35]
Hawkeye MVP was developed and deployed quickly in order to meet streaming event deadlines - which meant that we had to forgo some unit tests. We now have an opportunity to go back and create unit tests to ensure code coverage and stability long term.

<br/>

**Success Criteria:**

- 80% code coverage

<span data-href="#aha_task_list_start" data-version="v2" data-aha="Do not remove this tag. Used for Aha! syncing."/>

- [ ] <span data-href="#aha_task_list_HAWK-5-1" data-version="v2" data-aha="Do not remove this tag. Used for Aha! syncing."/> Refactor the API code to separate to isolate Kubernetes/External API calls
    <br/>

- [ ] <span data-href="#aha_task_list_HAWK-5-2" data-version="v2" data-aha="Do not remove this tag. Used for Aha! syncing."/> Write tests for the API 
    <br/>

- [ ] <span data-href="#aha_task_list_HAWK-5-3" data-version="v2" data-aha="Do not remove this tag. Used for Aha! syncing."/> Write tests for the workers
    <br/>
<span data-href="#aha_task_list_end" data-version="v2" data-aha="Do not remove this tag. Used for Aha! syncing."/>

Aha! Link: https://viacomcbs-digital.aha.io/features/HAWK-5
